const TRANSLATIONS = {
  en: {
    translation: {
      profile: "Profile",
      home: "Home",
      footer: "MyTaskManager list will help you to manage your tasks",
      serverError: "Server error",
      categories: "Categories",
      noCategories: "You have no categories",
      addCategory: "Create Category +",
      addTask: "Create task +",
      dateAndStatus: "Date and status",
      deadline: "Deadline:",
      deadlineFilters: "Deadline filters",
      completionStatus: "Completion status",
      sharedWith: "Shared with",
      linksAttacked: "links attached",
      name: "Name",
      email: "Email",
      registered: "Registered",
      logOut: "Log out",
      changePassword: "Change password",
      deleteAccount: "Delete account",
      showMyId: "Show my ID",
      day: "Day",
      week: "Week",
      month: "Month",
      year: "Year",
      all: "All",
      outdated: "Outdated",
      noDeadline: "No deadline",
      completed: "Completed",
      inProcess: "In process",
      categoryColor: "Category color",
      title: "Title",
      cancel: "Cancel",
      submit: "Submit",
      reallyСategory: "Do you really want to delete category?:",
      description: "Description",
      taskHasDeadline: "Task has deadline?",
      taskCompleted: "Task completed?",
      reallyTask: "Do you really want to delete task?:",
      additingLink: "Enter link you want to attach to",
      link: "Link",
      enterID: "Enter user ID to share with him",
      userID: "User ID",
      areYouSure: "Are you sure?",
      yes: "Yes",
      no: "No",
      password: "Password",
      newPassword: "New password",
      required: "Required",
      login: "Login",
      signIn: "Sign in",
      signUp: "Sign up",
      signUpBolt: "Sign up",
      enterPassword: "Enter password",
      confirmPassword: "Confirm password",
      statsLabel: "Completed Tasks",
      deadlineDay: "Day",
      deadlineWeek: "Week",
      deadlineMonth: "Month",
      deadlineYear: "Year",
      deadlineAll: "All",
      deadlineOutdated: "Outdated",
      deadlineNoDeadline: "No deadline",
      statusCompleted: "Completed",
      statusInProcess: "In process",
      statusAll: "All",
      noTask: "You have't tasks",
    },
  },
  ua: {
    translation: {
      profile: "Профіль",
      home: "Головна",
      footer: "MyTaskManager допоможе вам краще організувати свій час",
      serverError: "Помилка серверу",
      categories: "Категорії",
      noCategories: "У вас нема категорій",
      addCategory: "Додати категорію +",
      addTask: "Додати задачу +",
      dateAndStatus: "Дата і статус",
      deadline: "Строк:",
      deadlineFilters: "Фільтри за строком",
      completionStatus: "Статус виконання",
      sharedWith: "Ви поділилися з",
      linksAttacked: "Посилань прикріплено",
      name: "Ім'я",
      email: "Пошта",
      registered: "Створено",
      logOut: "Вийти",
      changePassword: "Змінити пароль",
      deleteAccount: "Видалити акаунт",
      showMyId: "Показати мій ID",
      day: "День",
      week: "Тиждень",
      month: "Місяць",
      year: "Рік",
      all: "Всі",
      outdated: "Прострочені",
      noDeadline: "Без дедлайну",
      completed: "Завершені",
      inProcess: "В процесі",
      categoryColor: "Колір категорії",
      title: "Назва",
      cancel: "Відміна",
      submit: "Підтвердити",
      reallyСategory: "Ви дійсно хочете видалити категорію?:",
      description: "Опис",
      taskHasDeadline: "Завдання має строк?",
      taskCompleted: "Завдання виконано?",
      reallyTask: "Ви дійсно хочете видалити завдання?:",
      additingLink: "Введіть посилання, яке хочете прикріпити",
      link: "Посилання",
      enterID: "Введіть ID користувача, щоб поділитися",
      userID: "ID користувача",
      areYouSure: "Ви впевнені?",
      yes: "Так",
      no: "Ні",
      password: "Пароль",
      newPassword: "Новий пароль",
      required: "Вимагається",
      loginBolt: "Вхід",
      signIn: "Увійти",
      signUp: "Зареєструватися",
      login: "Логін",
      signUpBolt: "Реєстрація",
      enterPassword: "Ввести пароль",
      confirmPassword: "Підтвердити пароль",
      statsLabel: "Завершені задачі",
      deadlineDay: "День",
      deadlineWeek: "Тиждень",
      deadlineMonth: "Місяць",
      deadlineYear: "Рік",
      deadlineAll: "Всі",
      deadlineOutdated: "Прострочені",
      deadlineNoDeadline: "Без дедлайну",
      statusCompleted: "Завершені",
      statusInProcess: "В процесі",
      statusAll: "Всі",
      noTask: "У вас нема задач",
    },
  },
};

export default TRANSLATIONS;
