const TRANSLATIONS = {
  en: {
    translation: {
      profile: "Profile",
      home: "Home",
      footer: "MyTaskManager list will help you to manage your tasks",
      serverError: "Server error",
      categories: "Categories",
      noCategories: "You have no categories",
      addCategory: "Create Category +",
      addTask: "Create task +",
      dateAndStatus: "Date and status",
      deadlineFilters: "Deadline filters",
      completionStatus: "Completion status",
      sharedWith: "Shared with",
      linksAttacked: "links attached",
      name: "Name",
      email: "Email",
      registered: "Registered",
      logOut: "Log out",
      changePassword: "Change password",
      deleteAccount: "Delete account",
      showMyId: "Show my id",
    },
  },
  ua: {
    translation: {
      profile: "Профіль",
      home: "Головна",
      footer: "МійТаскМенеджер допоможе вам краще організувати свій час",
      serverError: "Помилка серверу",
      categories: "Категорії",
      noCategories: "У вас нема категорій",
      addCategory: "Додати категорію +",
      addTask: "Додати задачу +",
      dateAndStatus: "Дата і статус",
      deadlineFilters: "Фільтри за дедлайном",
      completionStatus: "Статус виконання",
      sharedWith: "Ви поділилися з",
      linksAttacked: "Посилань прикріплено",
      name: "Ім'я",
      email: "Пошта",
      registered: "Створено",
      logOut: "Вийти",
      changePassword: "Змінити пароль",
      deleteAccount: "Видалити акаунт",
      showMyId: "Показати мій id",
    },
  },
};

export default TRANSLATIONS;
