import EN from "./languages/EN";
import UA from "./languages/UA";

export enum Status {
  LOADING = "loading",
  SUCCESS = "success",
  ERROR = "error",
}

export enum Theme {
  DARK = "dark",
  LIGHT = "light",
}

export enum Language {
  EN = "en",
  RU = "ru",
  UA = "ua",
}

export enum TranslationKeys {
  Profile = "profile",
  Home = "home",
  Footer = "footer",
  ServerError = "serverError",
  Categories = "categories",
  NoCategories = "noCategories",
  AddCategory = "addCategory",
  AddTask = "addTask",
  DateAndStatus = "dateAndStatus",
  Deadline = "deadline",
  DeadlineFilters = "deadlineFilters",
  CompletionStatus = "completionStatus",
  SharedWith = "sharedWith",
  LinksAttached = "linksAttached",
  Name = "name",
  Email = "email",
  Registered = "registered",
  LogOut = "logOut",
  ChangePassword = "changePassword",
  DeleteAccount = "deleteAccount",
  ShowMyId = "showMyId",
  Day = "day",
  Week = "week",
  Month = "month",
  Year = "year",
  All = "all",
  Outdated = "outdated",
  NoDeadline = "noDeadline",
  Completed = "completed",
  InProcess = "inProcess",
  CategoryColor = "categoryColor",
  Title = "title",
  Cancel = "cancel",
  Submit = "submit",
  ReallyCategory = "reallyСategory",
  Description = "description",
  TaskHasDeadline = "taskHasDeadline",
  TaskCompleted = "taskCompleted",
  ReallyTask = "reallyTask",
  AddingLink = "additingLink",
  Link = "link",
  EnterID = "enterID",
  UserID = "userID",
  AreYouSure = "areYouSure",
  Yes = "yes",
  No = "no",
  Password = "password",
  NewPassword = "newPassword",
  Required = "required",
  LoginBolt = "loginBolt",
  SignIn = "signIn",
  SignUp = "signUp",
  Login = "login",
  SignUpBolt = "signUpBolt",
  EnterPassword = "enterPassword",
  ConfirmPassword = "confirmPassword",
  StatsLabel = "statsLabel",
  DeadlineDay = "deadlineDay",
  DeadlineWeek = "deadlineWeek",
  DeadlineMonth = "deadlineMonth",
  DeadlineYear = "deadlineYear",
  DeadlineAll = "deadlineAll",
  DeadlineOutdated = "deadlineOutdated",
  DeadlineNoDeadline = "deadlineNoDeadline",
  StatusCompleted = "statusCompleted",
  StatusInProcess = "statusInProcess",
  StatusAll = "statusAll",
}
