export enum Status {
  LOADING = "loading",
  SUCCESS = "success",
  ERROR = "error",
}

export enum Theme {
  DARK = "dark",
  LIGHT = "light",
}

export enum Language {
  EN = "en",
  RU = "ru",
  UA = "ua",
}

export enum TranslationKeys {
  Profile = "profile",
  Home = "home",
  Footer = "footer",
  ServerError = "serverError",
  Categories = "categories",
  NoCategories = "noCategories",
  AddCategory = "addCategory",
  AddTask = "addTask",
  DateAndStatus = "dateAndStatus",
  Deadline = "deadline",
  DeadlineFilters = "deadlineFilters",
  CompletionStatus = "completionStatus",
  SharedWith = "sharedWith",
  LinksAttached = "linksAttached",
  Name = "name",
  Email = "email",
  Registered = "registered",
  LogOut = "logOut",
  ChangePassword = "changePassword",
  DeleteAccount = "deleteAccount",
  ShowMyId = "showMyId",
  Day = "day",
  Week = "week",
  Month = "month",
  Year = "year",
  All = "all",
  Outdated = "outdated",
  NoDeadline = "noDeadline",
  Completed = "completed",
  InProcess = "inProcess",
  CategoryColor = "categoryColor",
  Title = "title",
  Cancel = "cancel",
  Submit = "submit",
  ReallyCategory = "reallyСategory",
  Description = "description",
  TaskHasDeadline = "taskHasDeadline",
  TaskCompleted = "taskCompleted",
  ReallyTask = "reallyTask",
  AddingLink = "additingLink",
  Link = "link",
  EnterID = "enterID",
  UserID = "userID",
  AreYouSure = "areYouSure",
  Yes = "yes",
  No = "no",
  Password = "password",
  NewPassword = "newPassword",
  Required = "required",
  LoginBold = "loginBold",
  SignIn = "signIn",
  SignUp = "signUp",
  Login = "login",
  SignUpBold = "signUpBold",
  EnterPassword = "enterPassword",
  ConfirmPassword = "confirmPassword",
  StatsLabel = "statsLabel",
  DeadlineDay = "deadlineDay",
  DeadlineWeek = "deadlineWeek",
  DeadlineMonth = "deadlineMonth",
  DeadlineYear = "deadlineYear",
  DeadlineAll = "deadlineAll",
  DeadlineOutdated = "deadlineOutdated",
  DeadlineNoDeadline = "deadlineNoDeadline",
  StatusCompleted = "statusCompleted",
  StatusInProcess = "statusInProcess",
  StatusAll = "statusAll",
  Back = "<Back",
  FAQBold = "Frequently asked questions",
  Question1 = "How to start using MyTaskManager?",
  Question2 = "How to create a category?",
  Question3 = "How to create a task?",
  Question4 = "How to edit a task and/or category?",
  Question5 = "How to delete a task and/or category?",
  Question6 = "How to attach a link to a task?",
  Question7 = "How can I share a task with other users?",
  Question8 = "What filtering options are available for tasks?",
  Question9 = "How will the project develop in the future?",
  Question10 = "What are the moral values of the developers?",
  Answer1 = "Answer 1",
  Answer2 = "Answer 2",
  Answer3 = "Answer 3",
  Answer4 = "Answer 4",
  Answer5 = "Answer 5",
  Answer6 = "Answer 6",
  Answer7 = "Answer 7",
  Answer8 = "Answer 8",
  Answer9 = "Answer 9",
  Answer10 = "Answer 10",
}
